// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FQ-JbHbQRRD-qOB0Pw93jljhNQqoQAE',
    appId: '1:839234992413:web:ffd46f95961bd8df03c9f4',
    messagingSenderId: '839234992413',
    projectId: 'spend-sensor',
    authDomain: 'spend-sensor.firebaseapp.com',
    storageBucket: 'spend-sensor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5T2HqslVxh0qAEhzSuUeBc84OZWAVvIw',
    appId: '1:839234992413:android:0e7a20f53f7a0f7503c9f4',
    messagingSenderId: '839234992413',
    projectId: 'spend-sensor',
    storageBucket: 'spend-sensor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMms9aT_qF0ox_vMN2ty_C03Xaw0VQcA',
    appId: '1:839234992413:ios:0a1bc936186f84e303c9f4',
    messagingSenderId: '839234992413',
    projectId: 'spend-sensor',
    storageBucket: 'spend-sensor.firebasestorage.app',
    iosBundleId: 'com.example.spendsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMms9aT_qF0ox_vMN2ty_C03Xaw0VQcA',
    appId: '1:839234992413:ios:0a1bc936186f84e303c9f4',
    messagingSenderId: '839234992413',
    projectId: 'spend-sensor',
    storageBucket: 'spend-sensor.firebasestorage.app',
    iosBundleId: 'com.example.spendsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9FQ-JbHbQRRD-qOB0Pw93jljhNQqoQAE',
    appId: '1:839234992413:web:c00c3e3d6e1c335903c9f4',
    messagingSenderId: '839234992413',
    projectId: 'spend-sensor',
    authDomain: 'spend-sensor.firebaseapp.com',
    storageBucket: 'spend-sensor.firebasestorage.app',
  );
}
